name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python: [3.12, 3.13]
    runs-on: ${{ matrix.os }}
    name: Build with Python ${{ matrix.python }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: poetry
      - name: Install Dependencies
        run: poetry install --no-root
      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.12' }}
        run: poetry run task lint
      - name: Test
        run: poetry run task test
